version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
