export const FETCH_CURRENT_WORKOUT = 'FETCH_CURRENT_WORKOUT';
export const FETCH_CURRENT_WORKOUT_COMPLETE = 'FETCH_CURRENT_WORKOUT_COMPLETE';
export const SET_EXERCISE_VISIBILITY = 'SET_EXERCISE_VISIBILITY';
export const ADD_EXERCISE = 'ADD_EXERCISE';
